version: '3.8'
name: saame

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saame
    #ports:
    #  - "8080:80"
    restart: unless-stopped
    networks:
      - carmocc-nw

networks:
  carmocc-nw:
    external: true
